config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "pages#home"
  get 'about', to: "pages#about"
  resources :blogs
end 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/blog.rb
class Blog < ApplicationRecord

    validates :title, presence: true, length: { minimum: 4, maximum: 50}
    validates :description, presence: true, length: { minimum: 6, maximum: 500}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

    before_action :set_blog, only: [:show, :edit, :update, :destroy]

    def show
        
    end

    def index
        @blog = Blog.all
    end

    def new
        @blog = Blog.new
    end

    def edit
        
    end

    def create
        @blog = Blog.new(blog_params)
        if
            @blog.save
            flash[:notice]="Blog created successfully"
            redirect_to @blog
        else
            render "new"
        end
    end

    def update
        
        if
            @blog.update(blog_params)
            flash[:notice]="Blog updated successfully"
            redirect_to @blog
        else
            render "new"
        end
    end

    def destroy
        @blog.destroy
        redirect_to blogs_path
    end

    private
    def set_blog
        @blog = Blog.find(params[:id])
    end

    def blog_params
        params.require(:blog).permit(:title, :description)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

    def home 

    end

    def about

    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/blogs/_errors.html.erb
<% if @blog.errors.any? %>
    <h2>Following errors encountered</h2>
    <ul> 
        <% @blog.errors.full_messages.each do |msg| %> 
        <li> <%= msg %> </li>
        <%end%>
    </ul>
<%end%>

app/views/blogs/edit.html.erb
<h1>Edit the Blog</h1>

<%= render 'errors' %>

<%= form_with(model: @blog, local: true, data: {turbo: false}) do |f| %>

    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :description %> <br>
        <%= f.text_field :description %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<%end%>

<%= link_to "Cancle & return to all blogs", blogs_path %>

app/views/blogs/index.html.erb
<h3>
    <%= link_to "Home", root_path %> |
    <%= link_to "About", about_path %>
</h3>

<h1> Available Blogs</h1>

<table>
    <thead>
        <tr>
            <th>Title</th>
            <th>Description</th>
            <th colspan = '3' >Placeholder</th>
        </tr>
    </thead>
    <tbody>
        <% @blog.each do |blog| %>
        <tr>
            <td> <%= blog.title %> </td>
            <td> <%= blog.description %> </td>
            <td> <%= link_to "Show", blog_path(blog) %> </td>
            <td> <%= link_to "Edit", edit_blog_path(blog) %> </td>
            <td> <%= button_to "Delete", blog_path(blog), method: :delete, data: { confirm: "Are you sure"} %> </td>
        <%end%>
        </tr>
    </tbody>
</table>

<p>
    <%= link_to "Create New Blog", new_blog_path %>
</p>

app/views/blogs/new.html.erb
<h1>Create Blog</h1>

<%= render 'errors' %>

<%= form_with scope: :blog, url: blogs_path, data: {turbo: false}, local: true do |f| %>

    <p>
        <%= f.label :title %> <br>
        <%= f.text_field :title %>
    </p>

    <p>
        <%= f.label :description %> <br>
        <%= f.text_area :description %>
    </p>

    <p>
        <%= f.submit %>
    </p>
<%end%>

<%= link_to "Return to all blogs", blogs_path %>

app/views/blogs/show.html.erb
<h1>All Blogs</h1>

<p>Title: <strong> <%= @blog.title %> </strong></p>
<p>Description: <strong> <%= @blog.description %> </strong></p>

<p>
    <%= link_to "Edit", edit_blog_path(@blog) %>
    <%= button_to "Delete", blog_path(@blog), method: :delete, data: { confirm: "Are you sure"} %> 
</p>

<%= link_to "Return to all blogs", blogs_path %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg|%>
    <%= msg %>
<%end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DemoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <%= render 'layouts/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About page</h1>

<%= link_to "Home", root_path %> |
<%= link_to "Blogs", blogs_path %> 

app/views/pages/home.html.erb
<h1>Home page</h1>

<%= link_to "Blogs", blogs_path %> |
<%= link_to "About", about_path %>